name: Anchore Vulnerability Scan

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Build Management Center image
        run: |
          docker build -t hazelcast/management-center:${{ github.sha }} .

      - name: Scan Management Center image by Anchore
        if: always()
        uses: anchore/scan-action@v2.0.4
        with:
          image: hazelcast/management-center:${{ github.sha }}
          fail-build: true
      - name: grype scan JSON results
        run: for j in `ls ./anchore-reports/*.json`; do echo "---- ${j} ----"; cat ${j}; echo; done
