name: Build/Push Management Center image

on:
  create:
    tags:
      - 'v*'
    branches: 3.12.z

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set Release Version
        run: echo "RELEASE_VERSION=${GITHUB_REF:11}" >> $GITHUB_ENV
      - name: Print Release Version
        run: |
          echo ${{ env.RELEASE_VERSION }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1.2.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1.3.0
        with:
          version: v0.5.1

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build/Push Management Center image
        run: |
          docker buildx build --push \
            --tag hazelcast/management-center:${{ env.RELEASE_VERSION }} \
            --platform=linux/arm64,linux/amd64,linux/ppc64le,linux/s390x .
