name: Publish Management Center released version image

on:
  push:
    tags:
      - "v*.*"

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set Release Version
        run: echo "RELEASE_VERSION=${GITHUB_REF:11}" >> $GITHUB_ENV

      - name: Print Release Version
        run: echo ${{ env.RELEASE_VERSION }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2.0.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.0.0
        with:
          version: v0.8.2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Compute tags
        run: |
          TAGS="hazelcast/management-center:${{ env.RELEASE_VERSION }}"
          echo "TAGS=${TAGS}" >> $GITHUB_ENV

      - name: Print docker image tags
        run: echo ${{ env.TAGS }}

      - name: Build and push docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          tags: ${{ env.TAGS }}
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Update Docker Hub Description of Management Center image
        if: env.PUSH_LATEST == 'yes'
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: hazelcast/management-center
          short-description: Hazelcast Management Center Docker Image
          readme-filepath: ./README.md
